[package]
name = "hamming-wasm"
version = "0.1.0"
authors = ["Tiemen Waterreus <tiemen@tiemenwaterreus.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
web-sys = "0.3.46"
hamming = { git = "https://github.com/Tmw/hamming-rs.git" }
