on:
  push:
    branches:
      - master

jobs:
  check:
    name: check and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Run check
        run: cargo check

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build
        run: make build

      - name: see all
        run: ls -la static
