on:
  push:
    branches:
      - master

jobs:
  check:
    name: check and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin/wasm-pack
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build
        run: make build

      - name: Prepare for deploy
        run: | 
          mkdir dist
          cp static/index.html dist/index.html
          cp static/style.css dist/style.css
          cp static/wasm.js dist/wasm.js
          cp static/wasm_bg.wasm dist/wasm_bg.wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
